/**
 * Content-addressable URLs for the reference JSON assets in /public.
 *
 * GENERATED FILE — do not edit by hand. Regenerated by
 * `scripts/hash-public-assets.ts`, which runs as part of `npm run data`,
 * `npm run dev`, and `npm run build`.
 *
 * URLs are stable for any given source content. When the source content
 * changes the hash changes, so the URL changes, and any CDN/browser cache
 * is invalidated without us having to send revalidation headers.
 *
 * Hashed files in /public are served with
 * `Cache-Control: public, max-age=31536000, immutable` (see
 * `public/_headers` and `vercel.json`).
 */

export interface AssetManifest {
  aircraftMapping: string;
  airlines: string;
  airports: string;
  defraFactors: string;
  fuelBurn: string;
  gaiaAirports: string;
  gaiaCountries: string;
  seatConfigs: string;
}

export const ASSETS: AssetManifest = {
  aircraftMapping: "/aircraft-mapping.103c8632.json",
  airlines: "/airlines.eabd7897.json",
  airports: "/airports.e2f8790e.json",
  defraFactors: "/defra-factors.cde53aaf.json",
  fuelBurn: "/eea-fuel-burn.63813e0d.json",
  gaiaAirports: "/gaia-airports.be521ec3.json",
  gaiaCountries: "/gaia-countries.6f124d84.json",
  seatConfigs: "/seat-configs.111d91c2.json",
};
