/**
 * Generate content-hashed copies of the reference JSON assets and emit
 * `src/lib/asset-manifest.ts` mapping logical names to URLs.
 *
 * Source-of-truth JSONs live in `data/json/` (committed). The build hash
 * step reads each one, computes SHA-256, and writes a content-addressable
 * copy to `public/{name}.{hash8}.json`. Only the hashed copies are served
 * to the app — the CDN never sees the canonical names, so there are no
 * dead bytes on the wire.
 *
 * Pattern:
 *   - `data/json/airports.json`            (committed source)
 *   - `public/airports.e2f8790e.json`      (gitignored, regenerated, served)
 *
 * When source content changes the hash changes, the URL changes, and any
 * CDN/browser cache is invalidated without revalidation. Hashed files are
 * served with `Cache-Control: public, max-age=31536000, immutable` (see
 * `public/_headers`).
 *
 * Stale hashed files (from previous runs with different content) are
 * removed so we don't accumulate dead bytes in public/.
 *
 * Run: implicit via `npm run prebuild` / `npm run predev` / end of
 * `npm run data`. Idempotent.
 */

import { createHash } from "node:crypto";
import { readdirSync, readFileSync, unlinkSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

const REPO = resolve(fileURLToPath(import.meta.url), "../..");
const SRC_DIR = resolve(REPO, "data/json");
const PUBLIC_DIR = resolve(REPO, "public");
const MANIFEST_PATH = resolve(REPO, "src/lib/asset-manifest.ts");

/**
 * Map source filename → camelCase key used in the manifest + loader code.
 * Keep in sync with the `AssetManifest` interface.
 */
const SOURCE_TO_KEY: Record<string, string> = {
  "airports.json": "airports",
  "aircraft-mapping.json": "aircraftMapping",
  "eea-fuel-burn.json": "fuelBurn",
  "seat-configs.json": "seatConfigs",
  "gaia-airports.json": "gaiaAirports",
  "gaia-countries.json": "gaiaCountries",
  "defra-factors.json": "defraFactors",
};

const HASHED_RE = /^(.+)\.[0-9a-f]{8}\.json$/;

function shortHash(contents: Buffer): string {
  return createHash("sha256").update(contents).digest("hex").slice(0, 8);
}

interface ManifestEntry {
  key: string;
  source: string;
  hashed: string;
  hash: string;
}

function generateAll(): ManifestEntry[] {
  const files = readdirSync(SRC_DIR);
  const entries: ManifestEntry[] = [];

  for (const [source, key] of Object.entries(SOURCE_TO_KEY)) {
    if (!files.includes(source)) {
      console.warn(`  ! ${source} missing from data/json/ — skipping`);
      continue;
    }
    const buf = readFileSync(resolve(SRC_DIR, source));
    const hash = shortHash(buf);
    const hashed = `${source.replace(/\.json$/, "")}.${hash}.json`;
    const hashedPath = resolve(PUBLIC_DIR, hashed);
    writeFileSync(hashedPath, buf);
    entries.push({ key, source, hashed, hash });
  }
  return entries;
}

function pruneStale(entries: ManifestEntry[]): number {
  const wanted = new Set(entries.map((e) => e.hashed));
  let removed = 0;
  for (const file of readdirSync(PUBLIC_DIR)) {
    const match = HASHED_RE.exec(file);
    if (!match) continue;
    const baseName = `${match[1]}.json`;
    // Only prune if this base name is something we manage AND this specific
    // hashed file isn't the current one.
    if (!Object.keys(SOURCE_TO_KEY).includes(baseName)) continue;
    if (wanted.has(file)) continue;
    unlinkSync(resolve(PUBLIC_DIR, file));
    removed++;
  }
  return removed;
}

function writeManifest(entries: ManifestEntry[]): void {
  // Keep keys in a stable order — alphabetical for readability.
  const sorted = [...entries].sort((a, b) => a.key.localeCompare(b.key));
  const interfaceLines = sorted.map((e) => `  ${e.key}: string;`).join("\n");
  const valueLines = sorted.map((e) => `  ${e.key}: "/${e.hashed}",`).join("\n");

  const out = `/**
 * Content-addressable URLs for the reference JSON assets in /public.
 *
 * GENERATED FILE — do not edit by hand. Regenerated by
 * \`scripts/hash-public-assets.ts\`, which runs as part of \`npm run data\`,
 * \`npm run dev\`, and \`npm run build\`.
 *
 * URLs are stable for any given source content. When the source content
 * changes the hash changes, so the URL changes, and any CDN/browser cache
 * is invalidated without us having to send revalidation headers.
 *
 * Hashed files in /public are served with
 * \`Cache-Control: public, max-age=31536000, immutable\` (see
 * \`public/_headers\` and \`vercel.json\`).
 */

export interface AssetManifest {
${interfaceLines}
}

export const ASSETS: AssetManifest = {
${valueLines}
};
`;
  writeFileSync(MANIFEST_PATH, out);
}

function main(): void {
  console.log("Hashing data/json/*.json → emitting content-addressable copies to public/");
  const entries = generateAll();
  const pruned = pruneStale(entries);

  for (const e of entries) {
    console.log(`  ✓ ${e.source.padEnd(24)} → ${e.hashed}`);
  }
  if (pruned > 0) console.log(`  pruned ${pruned} stale hashed file(s)`);

  writeManifest(entries);
  console.log(`\nWrote ${MANIFEST_PATH} (${entries.length} entries)`);
}

main();
